# Text representation with Tf-Idf and basic IR models

### Implementing a Boolean Model

A boolean model takes in a query in boolean logic and returns the documents whose features match that query. Although simplistic, it is easy to implement, and can have varying applications.

In [1]:
from collections import Counter
import math
import re
import string

# !git clone https://github.com/mayank-02/boolean-retrieval-model.git
%cd boolean-retrieval-model/
from BooleanModel import BooleanModel

from datasets import load_dataset
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import pandas as pd
from rank_bm25 import BM25Okapi
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")

/Users/leander/Documents/github/leandroviajando/ir/boolean-retrieval-model

/opt/homebrew/anaconda3/envs/ir/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt to /Users/leander/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/leander/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/leander/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/leander/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
data =  ["Belgium is famous for chocolate, beer and waffle.",
        "Have you ever had Belgian fries?",
        "I have lived in Leuven for 4 years.",
        "I never liked chocolate on my waffle.",
        "Let's go out for some beers tonight."]

In [3]:
%mkdir -p toy_data

n=0
for line in data:
    with open (f'toy_data/text_{str(n)}.txt', "w") as outfile:
        outfile.write(line)
    n+=1

In [4]:
model = BooleanModel("./toy_data/*")

In [5]:
query = ("waffle | fries")  # Boolean logic: match documents containing the terms waffle OR fries

documents = model.query(query)

for file in documents:
  with open(f'toy_data/{file}') as f:
    print(f.read())

I never liked chocolate on my waffle.
Have you ever had Belgian fries?
Belgium is famous for chocolate, beer and waffle.

In [6]:
query = ("like | live")  # Boolean logic: match documents containing the terms like OR live

documents = model.query(query)

for file in documents:
  with open(f'toy_data/{file}') as f:
    print(f.read())

I have lived in Leuven for 4 years.
I never liked chocolate on my waffle.

### Calculating TfIdf (Term Frequency - Inverse Document Frequency)

TfIdf is a way to represent documents from frequency values based on how important a word is to a document in a collection.

**Step 1:** Preprocess the text to make it uniform, lower case, and remove punctuation so it is easy to work with.

In [7]:

def preprocess(list_of_text):
    preprocessed_text = []
    for text in list_of_text:
        text = text.translate(str.maketrans('', '', string.punctuation)) # remove punctuation
        text = text.lower() # convert to lower case
        words = word_tokenize(text) # tokenize the text
        preprocessed_text.append(words)
    return preprocessed_text

preprocessed_text = preprocess(data)

for text in preprocessed_text:
    print(text)

['belgium', 'is', 'famous', 'for', 'chocolate', 'beer', 'and', 'waffle']
['have', 'you', 'ever', 'had', 'belgian', 'fries']
['i', 'have', 'lived', 'in', 'leuven', 'for', '4', 'years']
['i', 'never', 'liked', 'chocolate', 'on', 'my', 'waffle']
['lets', 'go', 'out', 'for', 'some', 'beers', 'tonight']

**Step 2:** Calculate the term frequency for the data.
Term frequency can be calculated as the number of times a term appears in a document.

In [8]:
word_count = Counter(preprocessed_text[0])

print(word_count)

Counter({'belgium': 1, 'is': 1, 'famous': 1, 'for': 1, 'chocolate': 1, 'beer': 1, 'and': 1, 'waffle': 1})

Now for all the documents:

In [9]:
term_frequency = []
for text in preprocessed_text:
    word_count = Counter(text)
    term_frequency.append(word_count)

term_frequency = pd.DataFrame.from_dict(term_frequency, orient="columns")
term_frequency = term_frequency.fillna(0)
term_frequency

,belgium,is,famous,for,chocolate,beer,and,waffle,have,you,...,never,liked,on,my,lets,go,out,some,beers,tonight
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0

This is quite a sparse matrix with many 0 values. Can you think of a way to meaningfully reduce the size without losing much information?

Remove the stopwords! [Stopwords](https://smltar.com/stopwords) in this case can be defined as determiners, prepositions, conjunctions and other such words that do not add any content value to the document, and so can be removed.

Let's repreat the process now without the stopwords. NLTK has a predefined list of English stopwords that we can use.

In [10]:
def preprocess(list_of_text):
    preprocessed_text = []
    for text in list_of_text:
        text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
        text = text.lower()  # convert to lower case
        words = word_tokenize(text)  # tokenize the text
        words = [word for word in words if word not in stopwords.words('english')]  # remove stopwords
        preprocessed_text.append(words)
    return preprocessed_text

preprocessed_text = preprocess(data)
term_frequency = []
for text in preprocessed_text:
    word_count = Counter(text)
    term_frequency.append(word_count)

term_frequency = pd.DataFrame.from_dict(term_frequency, orient="columns")
term_frequency = term_frequency.fillna(0)
term_frequency

,belgium,famous,chocolate,beer,waffle,ever,belgian,fries,lived,leuven,4,years,never,liked,lets,go,beers,tonight
0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0

That's better!

**Step 3:** We can now use the term frequencies to calculate the inverse document frequency. Inverse document frequency is the log of the number of documents / number of documents containing the term.

In [11]:
idf = {}
for word in term_frequency.columns:
    idf[word] = math.log(len(preprocessed_text)/term_frequency[word].apply(lambda x: 1 if x > 0 else 0).sum())

idf = pd.DataFrame.from_dict(idf, orient="index").transpose()
idf

,belgium,famous,chocolate,beer,waffle,ever,belgian,fries,lived,leuven,4,years,never,liked,lets,go,beers,tonight
0,1.609438,1.609438,0.916291,1.609438,0.916291,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438,1.609438

**Step 4:** Calculate the tf-idf. Tf-idf is the product of the term frequency and the inverse document frequency.

In [12]:
tfidf_dict = {}
for i in range(len(preprocessed_text)):
    document_tfidf = []
    for column in idf:
        tfidf = term_frequency[column][i] * idf[column]
        document_tfidf.append(tfidf.values[0])
    tfidf_dict[f"Document {str(i)}"] = document_tfidf

tfidf_df = pd.DataFrame.from_dict(tfidf_dict, orient="index", columns = idf.columns)
tfidf_df = tfidf_df.round(2)
tfidf_df

,belgium,famous,chocolate,beer,waffle,ever,belgian,fries,lived,leuven,4,years,never,liked,lets,go,beers,tonight
Document 0,1.61,1.61,0.92,1.61,0.92,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Document 1,0.00,0.00,0.00,0.00,0.00,1.61,1.61,1.61,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Document 2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.61,1.61,1.61,1.61,0.00,0.00,0.00,0.00,0.00,0.00
Document 3,0.00,0.00,0.92,0.00,0.92,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.61,1.61,0.00,0.00,0.00,0.00
Document 4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.61,1.61,1.61,1.61

This pipeline we created has already been implemented in sklearn, so we can just use that!

In [13]:
vectorizer = TfidfVectorizer(stop_words="english")

In [14]:
analyze = vectorizer.build_analyzer()

In [15]:
print("Document 1", analyze(data[0]))
print("Document 2", analyze(data[1]))

Document 1 ['belgium', 'famous', 'chocolate', 'beer', 'waffle']
Document 2 ['belgian', 'fries']

In [16]:
X = vectorizer.fit_transform(data)
tfidf_df = pd.DataFrame(X.toarray(), index=range(len(data)), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.round(2)
tfidf_df

,beer,beers,belgian,belgium,chocolate,famous,fries,let,leuven,liked,lived,tonight,waffle,years
0,0.48,0.00,0.00,0.48,0.39,0.48,0.00,0.00,0.00,0.00,0.00,0.00,0.39,0.00
1,0.00,0.00,0.71,0.00,0.00,0.00,0.71,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.58,0.00,0.58,0.00,0.00,0.58
3,0.00,0.00,0.00,0.00,0.53,0.00,0.00,0.00,0.00,0.66,0.00,0.00,0.53,0.00
4,0.00,0.58,0.00,0.00,0.00,0.00,0.00,0.58,0.00,0.00,0.00,0.58,0.00,0.00

Do you note a difference in the tfidf values between the two matrices? This is because the sklearn implementation applies a **normalisation** to the `tf` (along with some **smoothing**), similar to what you have seen in class with length normalisation and augmented normalised term frequency.

How does that help?

This is to _avoid longer documents having higher tfidf weights across the vocabulary, since term frequency is sensitive to the length of the document_.

This matrix contains less words than the one we calculated manually. This is because the list of stop words defined in the nltk library is less exhaustive than the list defined in the sklearn implementation.

The size of this matrix can be reduced even further by lemmatizing the words. Lemmatizing is the process of converting words into their root form (beers --> beer). That way, when we search for 'beer', documents containing both 'beer' and 'beers' will be returned.

To do this, we can handle the entire preprocessing step ourselves, and pass the function we defined earlier to the vectorizer, after adding a lemmatizer.

In [17]:
def preprocess(doc):  # this takes in a string and converts it into a list
    doc = doc.split()
    lemmatizer = WordNetLemmatizer()
    preprocessed_text = []
    for text in doc:
        text = text.translate(str.maketrans("", "", string.punctuation))  # remove punctuation
        text = text.lower()  # convert to lower case
        words = word_tokenize(text)  # tokenize the text
        words = [word for word in words if word not in stopwords.words("english")]  # remove stopwords
        words = [lemmatizer.lemmatize(word) for word in words]  # lemmatize
        if words != []:
            preprocessed_text.append(words[0])
    return preprocessed_text

vectorizer = TfidfVectorizer(tokenizer=preprocess)
analyze = vectorizer.build_analyzer()
for idx, doc in enumerate(data):
    print(f"Document {idx}", analyze(doc))

Document 0 ['belgium', 'famous', 'chocolate', 'beer', 'waffle']
Document 1 ['ever', 'belgian', 'fry']
Document 2 ['lived', 'leuven', '4', 'year']
Document 3 ['never', 'liked', 'chocolate', 'waffle']
Document 4 ['let', 'go', 'beer', 'tonight']

In [18]:
X = vectorizer.fit_transform(data)
tfidf_df = pd.DataFrame(X.toarray(), index=range(len(data)), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.round(2)
tfidf_df

/opt/homebrew/anaconda3/envs/ir/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,4,beer,belgian,belgium,chocolate,ever,famous,fry,go,let,leuven,liked,lived,never,tonight,waffle,year
0,0.0,0.41,0.00,0.5,0.41,0.00,0.5,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.41,0.0
1,0.0,0.00,0.58,0.0,0.00,0.58,0.0,0.58,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.0
2,0.5,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.5,0.00,0.5,0.00,0.00,0.00,0.5
3,0.0,0.00,0.00,0.0,0.44,0.00,0.0,0.00,0.00,0.00,0.0,0.55,0.0,0.55,0.00,0.44,0.0
4,0.0,0.42,0.00,0.0,0.00,0.00,0.0,0.00,0.52,0.52,0.0,0.00,0.0,0.00,0.52,0.00,0.0

### Implementing a Vector Space Model

A vector space model takes a vector representation of the document and the query and ranks documents according to a similarity or distance measure between the query and document vector.

We will use the tf-idf weights we calculated above for our vector space model. The query can be represented as a simple binary vector where 1 represents the presence of a word and 0 represents the absense.

In [19]:
query = "beer and fries"
query = preprocess(query)  # preprocess the query before converting it into a vector

print(query)

['beer', 'fry']

We can now convert the query into a vector by passing it to the same vectorizer object we defined earlier:

In [20]:
# The vectorizer takes as input a list of queries - so here it will take ["beer fry"] as query.
# You can pass multiple queries as ["beer fry", "waffle fry"] which will return one vector for each query.
query_vector = vectorizer.transform([" ".join(query)])

print(query_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (1, 17)>
  Coords	Values
  (0, 1)	0.6279137616509933
  (0, 7)	0.7782829228046183

We will use cosine similarity to measure the similarity between the query and the documents, and rank the documents accordingly.

We pass the query vector and the tf-idf matrix, internally the `cosine_similarity` function will calculate the similarity between the query vector and each document vector and return scores.

In [21]:
cosine_similarities = cosine_similarity(query_vector, X)

results = [(data[i], cosine_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)

for doc, similarity in results:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 0.45
Have you ever had Belgian fries?

Similarity: 0.27
Let's go out for some beers tonight.

Similarity: 0.25
Belgium is famous for chocolate, beer and waffle.

Similarity: 0.00
I have lived in Leuven for 4 years.

Similarity: 0.00
I never liked chocolate on my waffle.

**Task:** Sklearn has implementations for more similarity and distance metrics such as Euclidean distance and Manhattan distance. Try using another metric and compare the difference in results.

In [22]:
from sklearn.metrics.pairwise import cosine_distances

cosine_distances_similarities = cosine_distances(query_vector, X)

results = [(data[i], cosine_distances_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)

for doc, similarity in results:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 1.00
I have lived in Leuven for 4 years.

Similarity: 1.00
I never liked chocolate on my waffle.

Similarity: 0.75
Belgium is famous for chocolate, beer and waffle.

Similarity: 0.73
Let's go out for some beers tonight.

Similarity: 0.55
Have you ever had Belgian fries?

In [23]:
from sklearn.metrics.pairwise import manhattan_distances  # L1 distance

manhattan_distances_similarities = manhattan_distances(query_vector, X)

results = [(data[i], manhattan_distances_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)

for doc, similarity in results:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 3.41
I have lived in Leuven for 4 years.

Similarity: 3.39
I never liked chocolate on my waffle.

Similarity: 2.82
Belgium is famous for chocolate, beer and waffle.

Similarity: 2.55
Let's go out for some beers tonight.

Similarity: 1.98
Have you ever had Belgian fries?

In [24]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances_similarities = euclidean_distances(query_vector, X)  # L2 distance

results = [(data[i], euclidean_distances_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)

for doc, similarity in results:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 1.41
I have lived in Leuven for 4 years.

Similarity: 1.41
I never liked chocolate on my waffle.

Similarity: 1.22
Belgium is famous for chocolate, beer and waffle.

Similarity: 1.21
Let's go out for some beers tonight.

Similarity: 1.05
Have you ever had Belgian fries?

In [25]:
from sklearn.metrics.pairwise import haversine_distances

haversine_distances_similarities = haversine_distances(query_vector, X)

results = [(data[i], haversine_distances_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)

for doc, similarity in results:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 0.61
Have you ever had Belgian fries?

Similarity: 0.57
I have lived in Leuven for 4 years.

Similarity: 0.37
Belgium is famous for chocolate, beer and waffle.

Similarity: 0.33
I never liked chocolate on my waffle.

Similarity: 0.25
Let's go out for some beers tonight.

### Implementing BM25 (Probabilistic model)

The Best-Match 25 algorithm follows the probabilistic retrieval framework, and uses term frequency and document length normalisation to determine the relevance of a document given a query. It operates with the underying assumption that a document generates a query.

The BM25 score for a document D with respect to a query Q is calculated as the sum of the scores for individual query terms. The formula for calculating the BM25 score is as follows:

$$BM25(D, Q) = ∑(IDF(q) * ((TF(q, D) * (k1 + 1)) / (TF(q, D) + k1 * (1 — b + b * (|D| / avgdl)))))$$

In this formula, $IDF(q)$ represents the inverse document frequency of the query term $q$, $TF(q, D)$ denotes the modified term frequency of term $q$ in document $D$, $\lvert D \rvert$ represents the length of document $D$, and $avgdl$ is the average document length in the corpus. Parameters $k1$ and $b$ are tunable constants that control the impact of term frequency saturation and document length normalization, respectively.

Note that BM25 measures TF and IDF differently. BM25 uses a modified term frequency that takes into account saturation effects to prevent overemphasizing heavily repeated terms. For IDF it assigns higher weights to terms that are rare in the corpus and lower weights to terms that are common.

Following is an implementation of the Okapi BM25 algorithm, taken from [this paper](http://www.cs.otago.ac.nz/homepages/andrew/papers/2014-2.pdf). To understand the implementation, see https://github.com/dorianbrown/rank_bm25/tree/master

Before we move ahead, we have to preprocess the data again since we added the lemmatizer to our preprocessing function.

In [26]:
preprocessed_text = [preprocess(doc) for doc in data]

In [27]:
bm25 = BM25Okapi(preprocessed_text)  # fit the model to the data

Let's define our query again:

In [28]:
query = "beer and fries"
query = preprocess(query)

We pass the preprocessed query and data to the model and rank documents accordingly:

In [29]:
# this returns an array of scores, where we can map the index to the index of the data to get the ranking
scores = bm25.get_scores(query)

score_to_id = {}
for i in range(len(scores)):
    score_to_id[str(i)] = float(scores[i])

ranking = sorted(score_to_id.items(), key=lambda x:x[1], reverse=True)

for k,v in ranking[:5]:
    print(f"Document: {data[int(k)]}\n Score: {v}")

Document: Have you ever had Belgian fries?
 Score: 1.23787300131618
Document: Let's go out for some beers tonight.
 Score: 0.33647223662121295
Document: Belgium is famous for chocolate, beer and waffle.
 Score: 0.30244695426625884
Document: I have lived in Leuven for 4 years.
 Score: 0.0
Document: I never liked chocolate on my waffle.
 Score: 0.0

**Task**: Try different queries.

In [30]:
# this returns an array of scores, where we can map the index to the index of the data to get the ranking
scores = bm25.get_scores(preprocess("Belgium"))

score_to_id = {}
for i in range(len(scores)):
    score_to_id[str(i)] = float(scores[i])

ranking = sorted(score_to_id.items(), key=lambda x:x[1], reverse=True)

for k,v in ranking[:5]:
    print(f"Document: {data[int(k)]}\n Score: {v}")

Document: Belgium is famous for chocolate, beer and waffle.
 Score: 0.9875166639713346
Document: Have you ever had Belgian fries?
 Score: 0.0
Document: I have lived in Leuven for 4 years.
 Score: 0.0
Document: I never liked chocolate on my waffle.
 Score: 0.0
Document: Let's go out for some beers tonight.
 Score: 0.0

### Exercise: Load your own data

For this exercise, you will load a subset of the [Simple English Wikipedia](https://simple.wikipedia.org/wiki/Main_Page), which is small and easy to load.

**Part 1**: Load the dataset and implement a boolean model, a vector space model
and a probabilistic model on the dataset for the following queries:

1. Earth's atmosphere
2. Agricultural crops
3. Parts of the human body
4. What are the official languages of countries?
5. Best places to travel

**Part 2**: Rank the documents and compare the top 5 results for each model. What differences do you see? Try passing longer queries to the models, for example, "Name parts of the human body" instead of "parts of the human body". Does that change the result?

**Part 3**: What happens to the results if you don't lemmatize or remove stop words?

**Part 4**: Try a different similarity measure for the vector space model. Which one returns more suitable results?

**Extra:**

- The BM25 repository provided above contains different variations of the BM25 algorithm - BM25L and BM25Plus. Use these models on the dataset and rank documents based on the queries defined. Compare the results.
- The hyperparameters k1 and b in the BM25 algorithm can be tuned. Test a couple of different values - can it be optimized further?

#### Dataset:

The Simple English Wikipedia can be loaded using the huggingface datasets library. We will only work with 200 articles from the dataset to save on computation time.

Note: You can increase the size of the subset to observe differences in the ranking of the retrieved documents.

In [31]:
data = load_dataset("wikipedia", "20220301.simple", trust_remote_code=True)["train"]
data = data.select(range(200))

In [32]:
print(data["text"][0])

April is the fourth month of the year in the Julian and Gregorian calendars, and comes between March and May. It is one of four months to have 30 days.

April always begins on the same day of week as July, and additionally, January in leap years. April always ends on the same day of the week as December.

April's flowers are the Sweet Pea and Daisy. Its birthstone is the diamond. The meaning of the diamond is innocence.

The Month

April comes between March and May, making it the fourth month of the year. It also comes first in the year out of the four months that have 30 days, as June, September and November are later in the year.

April begins on the same day of the week as July every year and on the same day of the week as January in leap years. April ends on the same day of the week as December every year, as each other's last days are exactly 35 weeks (245 days) apart.

In common years, April starts on the same day of the week as October of the previous year, and in leap years, May of the previous year. In common years, April finishes on the same day of the week as July of the previous year, and in leap years, February and October of the previous year. In common years immediately after other common years, April starts on the same day of the week as January of the previous year, and in leap years and years immediately after that, April finishes on the same day of the week as January of the previous year.

In years immediately before common years, April starts on the same day of the week as September and December of the following year, and in years immediately before leap years, June of the following year. In years immediately before common years, April finishes on the same day of the week as September of the following year, and in years immediately before leap years, March and June of the following year.

April is a spring month in the Northern Hemisphere and an autumn/fall month in the Southern Hemisphere. In each hemisphere, it is the seasonal equivalent of October in the other.

It is unclear as to where April got its name. A common theory is that it comes from the Latin word "aperire", meaning "to open", referring to flowers opening in spring. Another theory is that the name could come from Aphrodite, the Greek goddess of love. It was originally the second month in the old Roman Calendar, before the start of the new year was put to January 1.

Quite a few festivals are held in this month. In many Southeast Asian cultures, new year is celebrated in this month (including Songkran). In Western Christianity, Easter can be celebrated on a Sunday between March 22 and April 25. In Orthodox Christianity, it can fall between April 4 and May 8. At the end of the month, Central and Northern European cultures celebrate Walpurgis Night on April 30, marking the transition from winter into summer.

April in poetry
Poets use April to mean the end of winter. For example: April showers bring May flowers.

Events in April

Fixed Events

 April 1 - April Fools' Day
 April 1 - Islamic Republic Day (Iran)
 April 2 - International Children's Book Day
 April 2 - Thai Heritage and Conservation Day
 April 2 - World Autism Awareness Day
 April 2 - Malvinas Day (Argentina)
 April 4 - Independence Day (Senegal)
 April 4 - International Day for Landmine Awareness and Assistance
 April 4 - Peace Day (Angola)
 April 5 - End of Tax Year (United Kingdom)
 April 6 - Tartan Day (Canada and United States)
 April 6 - Chakri Day (Thailand)
 April 7 - Day of Maternity and Beauty (Armenia)
 April 7 - Genocide Memorial Day (Rwanda)
 April 7 - World Health Day
 April 7 - Women's Day (Mozambique)
 April 8 - Buddha's Birthday (Buddhism)
 April 9 - Martyrs' Day (Tunisia)
 April 9 - Day of National Unity (Georgia)
 April 9 - Day of the Finnish language
 April 12 - Cosmonauts' Day (Russia), marking the day of Yuri Gagarin's space flight
 April 13 - Songkan (Laos), local New Year celebration
 April 13 - Cambodian New Year
 April 13 - Thomas Jefferson's Birthday (United States)
 April 14 - Southeast Asian New Year festivals, including Songkran
 April 14 - Georgian language Day
 April 14 - Youth Day (Angola)
 April 14 - Ambedkar Tayanti (India)
 April 14 - Pan-American Day
 April 15 - Tax Day (United States)
 April 15 - Kim Il-Sung's Birthday (North Korea)
 April 15 - Father Damien Day (Hawaii)
 April 15 - Jackie Robinson Day (Major League Baseball)
 April 16 - Birthday of Queen Margrethe II of Denmark
 April 16 - Emancipation Day (Washington, DC)
 April 16 - World Voice Day
 April 16 - Selena Day (Texas)
 April 17 - National Day of Syria
 April 17 - Flag Day (American Samoa)
 April 17 - Women's Day (Gabon)
 April 17 - World Hemophilia Day
 April 18 - Independence Day (Zimbabwe)
 April 18 - Invention Day (Japan)
 April 18 - International Day of Monuments and Sites
 April 19 - Bicycle Day
 April 19 - Dutch-American Friendship Day
 April 19 - Birthday of King Mswati III of Swaziland
 April 19 - Patriots' Day (Massachusetts, Maine, Wisconsin)
 April 20 - 4/20 in Cannabis Culture
 April 21 - John Muir Day (California)
 April 21 - San Jacinto Day (Texas)
 April 21 - Kartini Day (Indonesia)
 April 21 - National Tree Planting Day (Kenya)
 April 21 - First Day of Ridran (Baha'i faith)
 April 21 - Grounation Day (Rastafari movement)
 April 22 - Earth Day
 April 22 - Discovery Day (Brazil)
 April 23 - Saint George's Day, celebrating the patron saint of several countries, regions and cities (including England and Catalonia)
 April 23 - World Book Day
 April 23 - National Sovereignty and Children's Day (Turkey)
 April 24 - Democracy Day (Nepal)
 April 24 - Genocide Day (Armenia)
 April 24 - Republic Day (the Gambia)
 April 25 - Australia and New Zealand celebrate ANZAC Day. ANZAC  means Australian and New Zealand Army Corps, and began in 1915.
 April 25 - World DNA Day
 April 25 - World Malaria Day
 April 25 - Flag Day (Swaziland, Faroe Islands)
 April 25 - Freedom Day (Portugal)
 April 25 - Liberation Day (Italy)
 April 25 - Army Day (North Korea)
 April 26 - Union Day (Tanzania)
 April 26 - Confederate Memorial Day (Texas, Florida)
 April 27 - Independence Day (Sierra Leone and Togo)
 April 27 - Freedom Day (South Africa)
 April 27 - World Tapir Day
 April 27 - King's Day (Netherlands) from 2014, birthday of Willem-Alexander of the Netherlands
 April 28 - Workers Memorial Day
 April 28 - National Day (Sardinia)
 April 28 - National Heroes Day (Barbados)
 April 29 - Showa Day (Japan), birthday of Emperor Hirohito, who died in 1989
 April 29 - International Dance Day
 April 30 - Former Queen's Day Holiday in the Netherlands (changed to King's Day, April 27 in 2014), was the birthday of former Queen Juliana of the Netherlands
 April 30 - Flag Day in Sweden (birthday of King Carl XVI Gustaf of Sweden)
 April 30 - International Jazz Day
 April 30 - Walpurgis Night (Central and Northern Europe)

Moveable Events

 Easter-related events in Western Christianity:
 Palm Sunday (between March 15 and April 18)
 Maundy Thursday (between March 19 and April 22)
 Good Friday (between March 20 and April 23)
 Easter Sunday (between March 22 and April 25)
 Easter Monday (between March 23 and April 26)
 Eastern Orthodox Easter falls between April 4 and May 8.
 Ascension Day (Western Christianity), falls between April 30 and June 3.
 Jewish Passover - falls in the same week as Western Christianity's Holy Week, which is the week leading up to Easter.
 Mother's Day (UK) falls between March 1 and April 4.
 World Snooker Championship (late April, early May)
 Horse racing - Grand National (UK), Kentucky Derby (United States)
 Start of Daylight Saving Time - Clocks going forward one hour:
 Most of Mexico
 Morocco (Ramadan does not include Daylight Saving Time)
 End of Daylight Saving Time - Clocks going back one hour:
 Southeast Australia, and New Zealand
 Chile
 Marathon Events in the following cities:
 Belgrade, Serbia
 Boston, Massachusetts, United States
 Brighton, United Kingdom
 Enschede, Netherlands
 London, United Kingdom
 Madrid, Spain
 Paris, France
 Rotterdam, Netherlands
 Utrecht, Netherlands
 Zurich, Switzerland

Selection of Historical Events

 April 1, 1918 - The Royal Air Force is founded.
 April 1, 1976 - Apple Inc. is founded.
 April 1, 1979 - The Islamic Republic of Iran is founded.
 April 1, 1999 - The territory of Nunavut is created in Northern Canada.
 April 1, 2001 - The Netherlands introduces same-sex marriage, as the first country to do so.
 April 2, 1519 - Florida is sighted by a European for the first time.
 April 2, 1930 - Haile Selassie becomes Emperor of Ethiopia.
 April 2, 1982 - Start of the Falklands War, as Argentine forces land on the Falkland Islands.
 April 2, 2005 - Pope John Paul II dies aged 84, after 26-and-a-half years as Pope.
 April 3, 1973 - The first-ever mobile phone call is placed by Martin Cooper in New York City.
 April 4, 1721 - Robert Walpole becomes the first Prime Minister of Great Britain.
 April 4, 1841 - William Henry Harrison dies. He was President of the United States for 31 days, the shortest-ever time in office for a US President.
 April 4, 1960 - Senegal becomes independent.
 April 4, 1968 - Assassination of Martin Luther King, Jr. in Memphis, Tennessee.
 April 5, 1722 - Jacob Roggeveen becomes the first European to land on Easter Island, landing there on Easter Sunday.
 April 6, 1320 - Scotland's independence is confirmed with the Declaration of Arbroath.
 April 6, 1830 - The Mormon Church is founded.
 April 6, 1909 - Robert Peary claims to have been first at the North Pole on this date.
 April 7, 1994 - The Rwandan Genocide begins.
 April 9, 1865 - American Civil War: Confederate forces under Robert E. Lee surrender to Union forces.
 April 9, 1940 - World War II: Denmark and Norway are invaded by Nazi Germany.
 April 9, 1989 - April 9 tragedy: In Tbilisi, Georgia, a peaceful demonstration for independence is broken up by the Soviet Army, killing 20 people. The country gains independence on this date exactly two years later.
 April 10, 1815 - Mount Tambora in Indonesia erupts in a huge eruption, affecting the world's climate for at least a year.
 April 10, 2010 - A plane crash near Smolensk, Russia, kills several people who were important in Poland, including President Lech Kaczynski.
 April 11, 1814 - Napoleon Bonaparte is exiled to the island of Elba.
 April 11, 1954 - Said to have been the most boring day of the 20th century.
 April 12, 1861 - The American Civil War begins at Fort Sumter, Charleston, South Carolina.
 April 12, 1945 - US President Franklin D. Roosevelt dies, and Harry S. Truman replaces him.
 April 12, 1961 - Yuri Gagarin becomes the first human to fly into space.
 April 14, 1865 - US President Abraham Lincoln is shot dead at Ford's Theatre by John Wilkes Booth. Lincoln dies the next day.
 April 14, 2010 - Qinghai Province, China, is hit by an earthquake, killing tens of thousands of people.
 April 14, 2010 - The eruption of Eyjafjallajokull in Iceland shuts down air traffic around Europe for a week, due to its ash cloud.
 April 15, 1912 - The ship RMS Titanic sinks near Newfoundland after hitting an iceberg, resulting in the deaths of many of the people on board.
 April 16, 1943 - Albert Hofmann discovers LSD's effects.
 April 17, 1946 - Syria gains full independence from France.
 April 18, 1906 - 1906 San Francisco earthquake: San Francisco, California, is hit by a big earthquake, resulting in fires that destroy large parts of the city.
 April 18, 1980 - Zimbabwe gains full independence.
 April 19, 1897 - The first Boston Marathon is held.
 April 19, 1971 - Sierra Leone becomes a republic.
 April 19, 1993 - The siege of the Branch Davidians at Waco, Texas, ends in a fire that kills 82 people.
 April 19, 1995 - Timothy McVeigh carries out the Oklahoma City bombing, killing 169 people.
 April 19, 2005 - Joseph Alois Ratzinger becomes Pope Benedict XVI.
 April 20, 1902 - Marie Curie and Pierre Curie refine Radium.
 April 20, 2010 - Deepwater Horizon oil spill: A massive fire on the Deepwater Horizon drilling rig in the Gulf of Mexico kills 11 workers and causes a massive oil spill, the worst spill in US history.
 April 21, 753 BC - Legendary founding date of Rome
 April 21, 1509 - Henry VIII of England becomes King.
 April 21, 1908 - Frederick Cook claims to have reached the North Pole on this date.
 April 22, 1502 - Pedro Alvares Cabral becomes the first European to reach present-day Brazil.
 April 22, 1970 - Earth Day is observed for the first time.
 April 23, 1533 - The Church of England declares that Henry VIII of England and Catherine of Aragon are not married.
 April 24, 1916 - The Easter Rising occurs in Dublin, Ireland.
 April 24, 1990 - The Hubble Space Telescope is launched on the Space Shuttle Discovery.
 April 25, 1915 - World War I: In Turkey, the Battle of Gallipoli begins, Australian, French, British and New Zealand forces land at Anzac cove.
 April 25, 1974 - Portugal's dictatorship is overthrown in a coup, in what is known as the Carnation Revolution.
 April 26, 1937 - Spanish Civil War: German planes bomb the town of Guernica, Basque Country, later depicted in a painting by Pablo Picasso.
 April 26, 1964 - Tanganyika and Zanzibar merge to form Tanzania.
 April 26, 1986 - A reactor explosion occurs at the Chernobyl nuclear plant in present-day Ukraine, with radiation spreading around Europe and the world.
 April 26/27, 1994 - South Africa holds its first free elections.
 April 27, 1960 - Togo becomes independent from France.
 April 27, 1961 - Sierra Leone becomes independent from the United Kingdom.
 April 28, 1789 - Mutiny on the ship Bounty in the Pacific Ocean, lead by Fletcher Christian.
 April 28, 1945 - Benito Mussolini is executed by Italian partisans.
 April 28, 1947 - In Peru, Thor Heyerdahl starts his Kon-Tiki expedition aimed at proving his theory that the Polynesian settlers on the Pacific Ocean's islands came from South America.
 April 29, 1991 - A cyclone in Bangladesh kills an estimated 138,000 people.
 April 29, 2011 - The wedding of Prince William, Duke of Cambridge and Catherine, Duchess of Cambridge is broadcast worldwide.
 April 30, 1789 - George Washington becomes the first President of the United States.
 April 30, 1803 - The United States purchases (buys) the Louisiana territory from France.
 April 30, 1945 - Adolf Hitler commits suicide on the same day that the Soviet Army raises the Red Flag on Berlin's Reichstag.
 April 30, 1952 - The Diary of Anne Frank is published in English.
 April 30, 1975 - The Vietnam War ends, as North Vietnamese forces take Saigon.
 April 30, 1980 - Queen Juliana of the Netherlands abdicates the throne, and her daughter becomes Queen Beatrix of the Netherlands. Beatrix later also abdicates, on this day in 2013, in favor of her son, King Willem-Alexander of the Netherlands.

Trivia

 In Western Christianity, there is a bigger likelihood of Easter falling in April than in March.
 The months around April (March and May) both start with an 'M' in the English language, with an 'A' as the second letter.
 In the English language, April is the first of three months in-a-row, along with May and June, that is also a female given name.
 The astrological signs for April are Aries (March 21 to April 20) and Taurus (April 21 to May 20).
 The sweet pea and daisy are the traditional birth flowers for April.
 Birthstone for April is the Diamond.
April 1 is the only day in April to start within the first quarter of the calendar year.
 If the months of the year were arranged in alphabetical order in the English language, April would come first.
 Six current European monarchs were born in April. They are King Philippe of Belgium (April 15), Queen Margrethe II of Denmark (April 16), Henri, Grand Duke of Luxembourg (April 16), Elizabeth II of the United Kingdom and Commonwealth realms (April 21), King Willem-Alexander of the Netherlands (April 27), and King Carl XVI Gustaf of Sweden (April 30).

References

In [33]:
# The implementation requies data in the form of text files, so let's create them.
# We will use the data ids provided for each article in the dataset as filenames so we can retrieve them later.

%mkdir data
for doc in data:
  with open (f"data/{doc['id']}.txt", "w") as outfile:
    outfile.write(doc["text"])

mkdir: data: File exists

In [34]:
model = BooleanModel("./data/*")

# Boolean logic
for query in [("earth & atmosphere"), ("agricultural & crops"), ("parts & human & body"),
              ("country & official & language"), ("travel & best & tourism")]:
    results = model.query(query)
    print(results)

['262.txt', '48.txt', '9.txt', '355.txt', '219.txt', '218.txt', '243.txt', '296.txt']
['102.txt', '80.txt', '280.txt', '294.txt', '19.txt']
['112.txt', '305.txt', '48.txt', '57.txt', '209.txt', '353.txt', '50.txt', '243.txt', '242.txt', '286.txt']
['262.txt', '103.txt', '248.txt', '12.txt', '104.txt', '89.txt', '361.txt', '363.txt', '208.txt', '54.txt', '178.txt', '52.txt', '185.txt', '53.txt', '292.txt', '27.txt', '291.txt']
['178.txt']

In [35]:
regex = re.compile(r'\d+')

result_ids = []
for result in results:
  id = regex.findall(result)[0]  # get the data ids from the filenames in the results
  result_ids.append(id)

for article in data:
  if article["id"] in result_ids:  # use the ids to get those datapoints from the dataset object
    print(f"{article}\n")

{'id': '178', 'url': 'https://simple.wikipedia.org/wiki/Cuba', 'title': 'Cuba', 'text': 'Cuba is an island country in the Caribbean Sea. The country is made up of the big island of Cuba, the Isla de la Juventud island (Isle of Youth), and many smaller islands. Havana is the capital of Cuba. It is the largest city. The second largest city is Santiago de Cuba. In Spanish, the capital is called "La Habana". Cuba is near the United States, Mexico, Haiti, Jamaica and the Bahamas. People from Cuba are called Cubans (cubanos in Spanish). The official language is Spanish. Cuba is warm all year.\n\nIn 1492, Christopher Columbus landed on the island of Cuba. He claimed it for the Kingdom of Spain. Cuba became a Spanish colony until the Spanish–American War of 1898. After the war, it was part of the United States. It gained independence in 1902.\n\nIn 1959, guerrilla fighters led by Fidel Castro and Che Guevara overthrew Cuba\'s dictator, Fulgencio Batista, in what became the Cuban Revolution. Castro began making relations with the Soviet Union and tried to close a lot of American businesses in Cuba; the United States did not like this. In 1961 Castro officially announced that his government was socialist. The US attempted to invade Cuba to regain control of it and overthrow its communist-led government but failed. The Communist Party of Cuba was created in 1965 and has ruled the island ever since. Today, Cuba is the only socialist state outside of Asia, in the Caribbean, and in the western hemisphere.\n\nCulture \nCuba is famous for many types of music, especially dance music such as the Salsa and Mambo. Because Cubans have ancestors from Spain, Africa, South America and North America, Cuban music is special and different.\n\nReading is very popular in Cuba. Many people especially enjoy reading books or things that come from outside the country, even though the government does not approve of this. They also love music and sports. Cuban music is very lively. This is because a lot of it comes from African and Spanish rhythms. Baseball, basketball, and athletics events are loved by many Cuban people. The Cheifs football-team took at one Football-World-Cup part. In 1938, they reached the quarter-final and lost against Sweden 0:8.\n\nHistory\n\nEarly history \nBefore Cuba was conquered by the Spaniards, three tribes lived on the island. They were the Taínos, the Ciboneys, and the Guanajatabeyes. The Taínos were the largest and most common of the three tribes. They farmed crops such as beans, corn, squash, and yams. The Taínos also slept in hammocks, which the Spaniards would introduce to the rest of the world. Then, in 1492, Christopher Columbus arrived in Cuba on his first trip to the Americas. Three years later, he claimed the islands for the Spanish. The Spanish began to rule Cuba afterwards. The Spanish brought thousands of slaves from Africa to Cuba to work for them. Most of the native Cubans died because of the new diseases brought by the Spanish and Africans. The Spanish also treated the native Cubans very cruelly and massacred many of them.\n\nThe Spanish ruled for many years. Cuba became the most important producer of sugar. In the early 1800s, Cubans rebelled against the Spanish rulers, but failed until 1898, when the United States went to war with the Spanish and defeated them. Cuba became American for four years afterwards, before it became an independent republic in 1902. Even though Cuba was independent, the Americans still controlled the island by a law called the Platt Amendment. In 1933 the Cubans stopped the Platt Amendment, but the Americans still had a big say in Cuban politics. Americans owned most of Cuba’s businesses. The Americans supported the leader Fulgencio Batista, who was seen by many Cubans as corrupt.\n\nIn addition to political control, the United States also exercised significant control over the Cuban economy. At the time, Cuba was a monoculture economy. While they produced coffee, tobacco, and rice, they relied primarily on sugar. Thus, they were known by other countries as the "sugar bowl of the world." The United States bought sugar from the Republic of Cuba at a price higher than the global standard. In exchange, Cuba was to give preference to the United States, and its industries. Cuba depended on the United States and their investments. Cuba was not industrialized and needed the revenue for goods and oil. They also needed the US investment for gas, electricity, communications, railways, and banks. While Cuban workers had better conditions than other countries in the continent, they still faced inequality, lack of infrastructure, high illiteracy rates, and a lack of full-time work (the sugar industry was seasonal).\n\nCuban Revolution \nIn 1959, Fidel Castro led a revolution against Fulgencio Batista. Castro took power in Cuba with Che Guevara from Argentina, his brother Raul, and others who fought against Batista. Castro made many changes to Cuba. He ended American ownership of Cuban businesses. This made Castro unpopular in America and the United States banned all contact with Cuba. Many Cubans went to America because of this. In 1961, the Americans helped some of these Cubans to attack Cuba and try to remove Castro, but they failed. Castro then asked the Soviet Union to help defend them from the Americans, which they did. The Soviet Union put nuclear weapons in Cuba and aimed them at the United States. American President Kennedy demanded that they be removed or a new war would begin. This was known as the Cuban Missile Crisis. The Soviet Union removed the missiles when the United States agreed to not continue attacking Cuba and to remove missiles from Turkey.\n\nCuba became a communist-led country like the Soviet Union after this. The Soviet Union bought most of Cuba’s sugar for expensive prices. Cuba spent this money on health, education and the army. This made Cuba’s schools and hospitals some of the best in the world. The army fought in Africa to support black Africans against the white South African army. Cuba also supported groups in South America fighting against the dictators of those countries.\n\nHowever, the Cuban government began to control most of life in Cuba under the communist system. Disagreeing with the Cuban government and Fidel Castro in public was not allowed. Some Cubans did not like this and tried to leave Cuba. Most Cubans who left went to the United States. Some Cubans who did not like the government and stayed were put in jail. Many groups from around the world protested against Cuba because of this, and demanded that Fidel Castro give up power.\n\nIn 1991, the Soviet Union collapsed. This meant that Cuba, which had sold most of its products to the Soviet Union, had no money coming into the country. The Americans made the restrictions against contact with Cuba tighter. America said the restrictions on contact would continue unless Fidel Castro gave up power. Cuba became very poor in the 1990s. This became known in Cuba as “The Special Period”. Because of the disaster, Cuba changed to allow less control by the government, more discussion amongst the people, and private shops and businesses. Cuba also tried to get tourists to visit the island.\n\nIn the 2000s, tourism to Cuba began to make money for the island again. Though Fidel Castro had remained in power, he had passed all duties to his brother Raul after an illness. Fidel Castro was one of the longest-serving heads of state. In 2018, Miguel Díaz-Canel became the official President of Cuba.\n\nIn April 2015, historic talks took place with US President Obama and Cuban General Secretary Raúl Castro in improving relations between the two nations.\n\nThe trade embargo issued by President Kennedy in the 1960s has been considerably loosened under Obama\'s administration. US citizens can now travel directly to Cuba at certain times of the year. Before, Americans had to go via Mexico if they wanted to go to Cuba. Americans are still not allowed to purchase or smoke Cuban cigars. The cigars are smuggled over the US-Canadian border since they are legal in Canada.\n\nFor military service, men from the age of 17 to 28 years old must go into the army for two years. It is optional for women.\n\nIn July 2021, there were demonstrations against the government.  See the English Wikipedia article, 2021 Cuban protests, for details.\n\nAdministrative divisions\n\nThe country is divided into 15 provinces and one special municipality (Isla de la Juventud). The provinces are divided into municipalities.\n\nDemographics \nThe population of Cuba is close to 13 million. The people of Cuba come from three different groups. The largest group is the descendants of the Spanish settlers who came to Cuba. The smallest group is the descendants of the black African slaves who were brought in to do the work and birth children (in the barracoon) as New World slaves who could be legally sold into life time bondage in the United States. The middle-sized group is a mix of African and Spanish. The government succeeded in seeing that the three different groups were treated the same. According to a DNA Caribbean Studies Institute, the racial-makeup of the population of Cuba is:\n European Cubans descend from settlers that came during the very late 15th century and onward. Most white Cubans came from many different parts of Spain, but the most numerous were the Canary Islanders, Andalusians, and Catalans. There was as well some French, Italian and English peoples. Whites makeup approximately 30% of Cuba\'s population as of 2012, and they mostly populate the western part of Cuba, specially cities like Havana and Pinar del Rio. These brought with them their language, religions, music and others.\n Africans and Mulatto Cubans descend from the arrival of African slaves that came from various parts of Africa but the most numerous were West Africans. There were also more than 500,000 Haitians that came to Cuba during the Haitian Revolution days. Most Cuban slaves tended to come from the Kongo and Yoruba tribes, there were also the Igbos, Ewes, Fons, Fulas, Mandinkas and some others. Afro-Cubans range enormously from 33.9 percent to 70 percent of the population, and they are mostly concentrated in the east parts of Cuba. These brought with them their instruments, reigion (Santeria), and customs to the Cuban culture.\n Mediterranean Cubans are about 3% of the population, however; one must know that a lot of the Southern Spaniard Cuban descendants have good portion of Moor blood in their family lines; due to the close proximate Spain is to North Africa. Many Mediterranean Cubans came during the 1820s-1880s and sometimes onward. These are most concentrated in the East specially cities like Guantanamo Bay. They brought much of their foods and cuisines to Cuba and a few vocabularies.\n\nHealth and education \nCuba is a developing country, and is often depicted as a very poor country. In some aspects, however, like education, health care and life expectancy it ranks much better than most countries in Latin America. Its infant death rate is lower than some developed countries. The average life expectancy is 78 years.\n\nAll the children are required to go to school from six to twelve years old, and nearly everybody is able to read and write at least. There is free education at every level. Because of this, Cuba has a 99.8% literacy rate.\n\nIn 2006, the World Food Programme certified Cuba to be the only country in this region without undernourished children. In the same year, the United Nations said that Cuba was the only nation in the world that met the World Wide Fund for Nature\'s definition of sustainable development.\n\nGeography \n\nCuba is the largest island in the West Indies. It has many resources. Only about one-fourth of the land is mountains or hills. Much of the land is gentle hills or plains which are good for farming or raising cattle. Cuba has fertile soil and a mostly warm and humid climate that makes it a great place for growing crops.\n\nSugar is the most important crop of Cuba, and they may get it from the sugar cane. Sugar cane is the largest cash crop grown in Cuba, and it brings in most of the money. After that, the second is tobacco. Tobacco is made into cigars by hand. A hand-made cigar is considered by many people to be the finest in the world. Other important crops are rice, coffee, and fruit. Cuba also has many minerals. Cobalt, nickel, iron, copper, and manganese are all on the island. Salt, petroleum, and natural gas are there too. The coast of Cuba has many bays and a few good harbors. Havana, which is the capital, is also a port. Other harbors have port cities. Nuevitas is a port city on the north coast. Cienfuegos, Guantánamo, and Santiago de Cuba are some of the port cities on the south coast.\n\nCuba has a semi-tropical climate. That means that the cool ocean winds keep it becoming hot, despite its being in the tropical zone. Cuba has a wet season and a dry season. The dry season is from November to April, and the wet season is from May to October. August to October is also the hurricane season in the Atlantic Ocean. Because of this, most of Cuba\'s port cities can be flooded along the coast.\n\nRelated pages \n Cuba at the Olympics\n Cuba national football team\n List of rivers of Cuba\n :Category:Cuban people\n\nReferences \n\n \nSpanish-speaking countries\nCaribbean Community'}

This type of model can be fast and efficient, since it is just doing literal string matching. For applications where you just want to do a keyword search, for example, this is very good.

Moreover, it lets you also define words that you do not want to appear in the documents, which is not possible in the vector space or probabilistic models.

On the other hand, you have to be able to fit your queries into the structure of boolean logic. This becomes difficult for longer, more complex queries.

**Implementing a Vector Space Model**:

A vector space model takes a vector representation of the document and the query, and ranks documents according to a similarity or distance measure between the query and document vector.

We will use the tf-idf weights we calculated above for our vector space model. The query can be represented as a simple binary vector where 1 represents the presence of a word and 0 represents its absense. In this implementation, the query vector is basically a vector of the size of the vocabulary of the corpus, with a tfidf weight assigned to the words present in the query.

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer


def preprocess(doc: str) -> list:
    doc = doc.split()
    digits = re.compile(r'\d')
    lemmatizer = WordNetLemmatizer()
    preprocessed_text = []
    for text in doc:
        text = text.translate(str.maketrans("", "", string.punctuation))  # remove punctuation
        text = text.lower()  # convert to lower case
        words = word_tokenize(text)  # tokenize the text
        words = [word for word in words if word not in stopwords.words("english")]  # remove stopwords
        words = [word for word in words if not digits.match(word)]  #  additional step : removing digits
        words = [lemmatizer.lemmatize(word) for word in words]  # lemmatize
        if words != []:
            preprocessed_text.append(words[0])
    return preprocessed_text

vectorizer = TfidfVectorizer(tokenizer=preprocess)
X = vectorizer.fit_transform(data["text"])
tfidf_df = pd.DataFrame(X.toarray(), index=range(len(data)), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.round(2)
tfidf_df

/opt/homebrew/anaconda3/envs/ir/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,aaa,aalto,aave,abacus,abalone,abandoned,abbasids,abbey,abbott,abbreviated,...,€725,→,−,≠,八百万の神,大都,姬,市,燕,蓟
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.02,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
query = "Earth's atmosphere"
query = "Agricultural crops"
query = "Parts of the human body"
query = "What are the official languages of countries?"
query = "name parts of the human body."
query = "Best places to travel as a tourist"

query = preprocess(query)
print(query)

['best', 'place', 'travel', 'tourist']

In [38]:
query_vector = vectorizer.transform([" ".join(query)])
print(query_vector)
print(query_vector.toarray())  # this is the actual vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (1, 11033)>
  Coords	Values
  (0, 1051)	0.5079227478218901
  (0, 7521)	0.333789303173216
  (0, 10061)	0.595398887797236
  (0, 10119)	0.5254515655529196
[[0. 0. 0. ... 0. 0. 0.]]

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarities = cosine_similarity(query_vector, X)
results = [(data[i], cosine_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)
for doc, similarity in results[:5]:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 0.05
{'id': '182', 'url': 'https://simple.wikipedia.org/wiki/Cost%20of%20living', 'title': 'Cost of living', 'text': 'Cost of living is the amount of money it costs just to live in a certain place.  It includes food, housing, etc.\n\nEconomics'}

Similarity: 0.05
{'id': '186', 'url': 'https://simple.wikipedia.org/wiki/Dublin', 'title': 'Dublin', 'text': 'Dublin () is the capital of the Republic of Ireland, and the biggest city on the island of Ireland. In 2011, there were over 1.1 million people living in the Greater Dublin Area.\n\nDublin was built by the Vikings upon the river Liffey. The river divides the city into two parts, North Dublin and South Dublin.\n\nMany famous writers lived in Dublin. Oscar Wilde and George Bernard Shaw were born in Dublin. James Joyce is probably Dublin\'s best known and most international writer.\n\nDublin is home to Ireland\'s largest stadium for all sports, Croke Park. It can hold up to 85,000 people. Croke Park is the usual venue for all Ireland hurling and football finals. The Aviva Stadium hosts rugby and soccer.\n\nNotes\n\nReferences\n\nOther websites \n\n "The Reflecting City"\n Dublin GDP stats \n WikiSatellite view of Dublin at WikiMapia\n The Dublin Community Blog\n Satellite map of Dublin - Including local geographic features.\n Dublin - Tourist information.\n\n \nCounty towns in Ireland'}

Similarity: 0.05
{'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}

Similarity: 0.05
{'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}

Similarity: 0.04
{'id': '335', 'url': 'https://simple.wikipedia.org/wiki/Hawaii%20%28island%29', 'title': 'Hawaii (island)', 'text': 'The Island of Hawaiʻi is the largest U.S. Hawaiian Island, and it is the farthest south. It is also called the "Big Island." Its area is 4,038 sq. miles (10,458 km2). The widest part of the island is 93 miles (150 km) across.\nThe Big Island has more than half (~62%) of the total land area of State of Hawaii. It is part of County of Hawaii.\n\nThe island is seven separate shield volcanos that erupted more or less one at a time, one partly covering the other. These are (from oldest to youngest): Kohala (extinct), Mauna Kea (dormant), Hualalai (dormant), Mauna Loa (active), Kulani (extinct, mostly buried), and Kilauea (very active). The volcanos were caused by the Pacific oceanic tectonic plate moving over a hotspot. There lava from the Earth\'s lower mantle or upper core is close to the surface.\n\nThe largest city on the island is Hilo. Hilo has many historic buildings, interesting shops, parks, many performances, festivals and events. It is on the rainy, east side of the island. The city of Kailua-Kona is on the dry, west side of Hawaii, and is popular with tourists.\n\nReferences\n\nMacDonald, G. A., and A. T. Abbott. 1970. Volcanoes in the Sea. Univ. of Hawaii Press, Honolulu. 441 p.\nHistory and culture of Hilo. (2010). Retrieved from http://www.hiloliving.com/Hilo_Culture.html\n\nIslands of Hawaii'}

In [40]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_dist = euclidean_distances(query_vector, X)
results = [(data[i], euclidean_dist[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1])
for doc, similarity in results[:5]:
    print(f"Distance: {similarity:.2f}\n{doc}\n")

Distance: 1.38
{'id': '182', 'url': 'https://simple.wikipedia.org/wiki/Cost%20of%20living', 'title': 'Cost of living', 'text': 'Cost of living is the amount of money it costs just to live in a certain place.  It includes food, housing, etc.\n\nEconomics'}

Distance: 1.38
{'id': '186', 'url': 'https://simple.wikipedia.org/wiki/Dublin', 'title': 'Dublin', 'text': 'Dublin () is the capital of the Republic of Ireland, and the biggest city on the island of Ireland. In 2011, there were over 1.1 million people living in the Greater Dublin Area.\n\nDublin was built by the Vikings upon the river Liffey. The river divides the city into two parts, North Dublin and South Dublin.\n\nMany famous writers lived in Dublin. Oscar Wilde and George Bernard Shaw were born in Dublin. James Joyce is probably Dublin\'s best known and most international writer.\n\nDublin is home to Ireland\'s largest stadium for all sports, Croke Park. It can hold up to 85,000 people. Croke Park is the usual venue for all Ireland hurling and football finals. The Aviva Stadium hosts rugby and soccer.\n\nNotes\n\nReferences\n\nOther websites \n\n "The Reflecting City"\n Dublin GDP stats \n WikiSatellite view of Dublin at WikiMapia\n The Dublin Community Blog\n Satellite map of Dublin - Including local geographic features.\n Dublin - Tourist information.\n\n \nCounty towns in Ireland'}

Distance: 1.38
{'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}

Distance: 1.38
{'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}

Distance: 1.39
{'id': '335', 'url': 'https://simple.wikipedia.org/wiki/Hawaii%20%28island%29', 'title': 'Hawaii (island)', 'text': 'The Island of Hawaiʻi is the largest U.S. Hawaiian Island, and it is the farthest south. It is also called the "Big Island." Its area is 4,038 sq. miles (10,458 km2). The widest part of the island is 93 miles (150 km) across.\nThe Big Island has more than half (~62%) of the total land area of State of Hawaii. It is part of County of Hawaii.\n\nThe island is seven separate shield volcanos that erupted more or less one at a time, one partly covering the other. These are (from oldest to youngest): Kohala (extinct), Mauna Kea (dormant), Hualalai (dormant), Mauna Loa (active), Kulani (extinct, mostly buried), and Kilauea (very active). The volcanos were caused by the Pacific oceanic tectonic plate moving over a hotspot. There lava from the Earth\'s lower mantle or upper core is close to the surface.\n\nThe largest city on the island is Hilo. Hilo has many historic buildings, interesting shops, parks, many performances, festivals and events. It is on the rainy, east side of the island. The city of Kailua-Kona is on the dry, west side of Hawaii, and is popular with tourists.\n\nReferences\n\nMacDonald, G. A., and A. T. Abbott. 1970. Volcanoes in the Sea. Univ. of Hawaii Press, Honolulu. 441 p.\nHistory and culture of Hilo. (2010). Retrieved from http://www.hiloliving.com/Hilo_Culture.html\n\nIslands of Hawaii'}

Both similarity metrics return the same rankings.

Okapi BM25 (Probabilistic model)

In [41]:
preprocessed_text = [preprocess(doc) for doc in data["text"]]

In [42]:
bm25 = BM25Okapi(preprocessed_text)

In [43]:
query = "Earth's atmosphere"
query = "Agricultural crops"
query = "Parts of the human body"
query = "What are the official languages of countries?"
query = "name parts of the human body."
query = "Best places to travel as a tourist"

query = preprocess(query)
print(query)

['best', 'place', 'travel', 'tourist']

In [44]:
doc_scores = bm25.get_scores(query)

score_to_id = {}
for i in range(len(doc_scores)):
  score_to_id[str(i)] = float(doc_scores[i])

ranking = sorted(score_to_id.items(), key=lambda x:x[1], reverse=True)

for k,v in ranking[:5]:
  print(f"Document: {data[int(k)]}\n Score: {v}\n")

Document: {'id': '186', 'url': 'https://simple.wikipedia.org/wiki/Dublin', 'title': 'Dublin', 'text': 'Dublin () is the capital of the Republic of Ireland, and the biggest city on the island of Ireland. In 2011, there were over 1.1 million people living in the Greater Dublin Area.\n\nDublin was built by the Vikings upon the river Liffey. The river divides the city into two parts, North Dublin and South Dublin.\n\nMany famous writers lived in Dublin. Oscar Wilde and George Bernard Shaw were born in Dublin. James Joyce is probably Dublin\'s best known and most international writer.\n\nDublin is home to Ireland\'s largest stadium for all sports, Croke Park. It can hold up to 85,000 people. Croke Park is the usual venue for all Ireland hurling and football finals. The Aviva Stadium hosts rugby and soccer.\n\nNotes\n\nReferences\n\nOther websites \n\n "The Reflecting City"\n Dublin GDP stats \n WikiSatellite view of Dublin at WikiMapia\n The Dublin Community Blog\n Satellite map of Dublin - Including local geographic features.\n Dublin - Tourist information.\n\n \nCounty towns in Ireland'}
 Score: 7.90850977640666

Document: {'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}
 Score: 5.018892087649618

Document: {'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}
 Score: 4.692076175390117


While the top 3 or 4 ranked documents are the same for both vector space and probabilistic models (they both use tfidf, although with different variations) the differences in the models come out when we go down the rankings.

Although just based on word frequencies, tfidf can be a powerful representation that is able to identify relevance in a meaningful manner.

**What happens to the tfidf matrix if you don't preprocess the text? How does that affect the results from your vector space model?**

In [45]:
def preprocess(doc):   #this takes in a string and converts it into a list
    doc = doc.split()
    # preprocessed_text = []
    # for text in doc:
    #     text = text.translate(str.maketrans('', '', string.punctuation)) #remove punctuation
    #     text = text.lower() #convert to lower case
    #     words = word_tokenize(text) #tokenize the text
    #     words = [word for word in words if word not in stopwords.words('english')] #remove stopwords
    #     words = [lemmatizer.lemmatize(word) for word in words] #lemmatize
    #     if words != []:
    #         preprocessed_text.append(words[0])
    return doc

vectorizer = TfidfVectorizer(tokenizer=preprocess)
X = vectorizer.fit_transform(data['text'])
tfidf_df = pd.DataFrame(X.toarray(), index=range(len(data)), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.round(2)
tfidf_df

/opt/homebrew/anaconda3/envs/ir/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,"""","""""",""""",","""&"",","""&c""","""+""","""+"",",""".","""...knödel"";","""...nudln""",...,€2.64,€23.5,€3.1,"€451,000",€56,€7.25,→,−,≠,市
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

You will observe that there is a lot of noise retained in the matrix that does not add any value to the representations.

You are essentially storing noise and adding compute time, and assigning weights to words/characters that are irrelevant.

You can try running the queries again to see how that impacts the type of documents your model will return.

In [46]:
query = "Earth's atmosphere"
query = "Agricultural crops"
query = "Parts of the human body"
query = "What are the official languages of countries?"
query = "name parts of the human body."
query = "Best places to travel as a tourist"

query = preprocess(query)
print(query)

['Best', 'places', 'to', 'travel', 'as', 'a', 'tourist']

The query also retains the stop words - so you will be computing similarities for 'of' and 'the' that add no additional information to the meaning of your query - they just serve a grammatical purpose.

Vector Space Model

In [47]:
query_vector = vectorizer.transform([" ".join(query)])
print(query_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 20656)>
  Coords	Values
  (0, 2524)	0.12939466803678873
  (0, 3598)	0.16237442934105703
  (0, 4259)	0.43364021029270233
  (0, 14950)	0.43364021029270233
  (0, 18959)	0.1360081192592064
  (0, 19073)	0.5865693839850251
  (0, 19157)	0.46716383623030877

In [48]:
cosine_similarities = cosine_similarity(query_vector, X)
results = [(data[i], cosine_similarities[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1], reverse=True)
for doc, similarity in results[:5]:
    print(f"Similarity: {similarity:.2f}\n{doc}\n")

Similarity: 0.10
{'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}

Similarity: 0.07
{'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}

Similarity: 0.07

In [49]:
euclidean_dist = euclidean_distances(query_vector, X)
results = [(data[i], euclidean_dist[0][i]) for i in range(len(data))]
results.sort(key=lambda x: x[1])
for doc, similarity in results[:5]:
    print(f"Distance: {similarity:.2f}\n{doc}\n")

Distance: 1.34
{'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}

Distance: 1.36
{'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}

Distance: 1.36

Probabilistic Model

In [50]:
preprocessed_text = [preprocess(doc) for doc in data['text']]

In [51]:
bm25 = BM25Okapi(preprocessed_text)

In [52]:
doc_scores = bm25.get_scores(query)

score_to_id = {}
for i in range(len(doc_scores)):
    score_to_id[str(i)] = float(doc_scores[i])

ranking = sorted(score_to_id.items(), key=lambda x:x[1], reverse=True)

for k,v in ranking[:5]:
    print(f'Document: {data[int(k)]}\n Score: {v}\n')

Document: {'id': '144', 'url': 'https://simple.wikipedia.org/wiki/City', 'title': 'City', 'text': 'A city is a heavily inhabited community that may include structures, buildings, bridges, rivers or lakes, and landmarks.\n\nA city has many buildings and streets. It has houses, hotels, condominiums, and apartments for many people to live in, shops where they may buy things, places for people to work, and a government to run the city and keep law and order in the city. People live in cities because it is easy for them to find and do everything they want there. A city usually has a "city center" where government and business occur and suburbs where people live outside the center.\n\nDefinition\n\nNo rule is used worldwide to decide why some places are called "city," and other places are called "town."\n\nSome things that make a city are :\n A long history. Although many cities today have only been around for tens or hundreds of years, there are a few which have been so for thousands of years. For example, Athens, Greece was founded in 1000 BC and Rome, Italy has existed since 700 BC.\n A large population. Cities can have millions of people living in and around them. Among them are Tokyo, Japan, and the Tokyo Metropolis around it, which includes Yokohama and Chiba.\n In Japan, the population of a city ( 市 ) is at least over 50,000 persons. and among cities, there are various grades according to laws, which the central government of Japan governs.\n A center where business and government takes place. The first case is often described as the financial capital, such as Frankfurt in Germany. The second case is true for different levels of government, whether they are local or part of a larger region (for example, Atlanta, Georgia, or the capital of the United States Washington, D.C.) Cities that contain the government of the region it is in are called capitals. Almost every country has its own capital.\n Special powers called town privileges which have been given by the government of the country or its ruler. Europe during the Middle Ages was a great example of having town privileges.\n Having a cathedral or a university. This rule is found in the United Kingdom. The smallest "cathedral cities" are St. David\'s and St. Asaph\'s which are both in Wales, Ripon and Wells which are in England.\n\nIn American English, people often call all places where many people live cities. (See below: Size of cities )\n\nSize of cities\n\nThe sizes of cities can be very different. This depends on the type of city. Cities built hundreds of years ago and which have not changed much are much smaller than modern cities. There are two main reasons. One reason is that old cities often have a city wall, and most of the city is inside it. Another important reason is that the streets in old cities are often narrow. If the city got too big, it was hard for a cart carrying food to get to the marketplace. People in cities need food, and the food always has to come from outside the city.\n\nCities that were on a river like London could grow much bigger than cities that were on a mountain like Sienna in Italy, because the river made a transport route for carrying food and other goods, as well as for transporting people. London has been changing continually for hundreds of years, while Sienna, a significant city in the 1300s, has changed very little in 700 years.\n\nModern cities with modern transport systems can grow very large, because the streets are wide enough for cars, buses, and trucks, and there are often railway lines.\n\nIn the US, the word city is often used for towns that are not very big. When the first European people went to America, they named " city " to new places. They hoped the places would be great cities in the future. For example, Salt Lake City was the name given to a village of 148 people. When they started building the town, they made street plans and called it Great Salt Lake City (for the nearby Great Salt Lake).\n\nNow, 150 years later, it really is a big city.\n\nIn modern times many cities have grown bigger and bigger. The whole area is often called a  "metropolis"  and can sometimes include several small ancient towns and villages. The metropolis of London includes London, Westminster, and many old villages such as Notting Hill, Southwark, Richmond, Greenwich, etc. The part that is officially known as the " City of London " only takes up one square mile. The rest is known as "Greater London. " Many other cities have grown in the same way.\n\nThese giant cities can be exciting places to live, and many people can find good jobs there, but modern cities also have many problems. Many people cannot find jobs in the cities and have to get money by begging or by crime. Automobiles, factories, and waste create a lot of pollution that makes people sick.\n\nUrban history \n\nUrban history is history of civilization. The first cities were made in ancient times, as soon as people began to create civilization . Famous ancient cities which fell to ruins included Babylon, Troy, Mycenae and Mohenjo-daro.\n\nBenares in northern India is one among the ancient cities which has a history of more than 3000 years. Other cities that have existed since ancient times are Athens in Greece, Rome and Volterra in Italy, Alexandria in Egypt and York in England.\n\nIn Europe, in the Middle Ages, being a city was a special privilege, granted by nobility. Cities that fall into this category, usually had (or still have) city walls. The people who lived in the city were privileged over those who did not. Medieval cities that still have walls include Carcassonne in France, Tehran in Iran, Toledo in Spain and Canterbury in England.\n\nFeatures\n\nInfrastructure \n\nPeople in a city live close together, so they cannot grow all their own food or gather their own water or energy. People also create waste and need a place to put it. Modern cities have infrastructure to solve these problems. Pipes carry running water, and power lines carry electricity. Sewers take away the dirty water and human waste. Most cities collect garbage to take it to a landfill, burn it, or recycle it.\n\nTransport is any way of getting from one place to another. Cities have roads which are used by automobiles (including trucks), buses, motorcycles, bicycles, and pedestrians (people walking). Some cities have trains and larger cities have airports. Many people in cities travel to work each day, which is called commuting.\n\nBuildings and design \nHouses and apartments are common places to live in cities. Great numbers of people in developing countries (and developed countries, in the past) live in slums. A slum is poorly built housing, without clean water, where people live very close together. Buildings are usually taller in the city center, and some cities have skyscrapers.\n\nCity streets can be shaped like a grid, or as a "wheel and spokes": a set of rings and lines coming out from the center. Streets in some older cities like London are arranged at random, without a pattern. The design of cities is a subject called urban planning. One area of the city might have only shops, and another area might have only factories. Cities have parks, and other public areas like city squares.\n\nUnited States politics\n\nCities in the US are usually very-left leaning. The best examples of these would be New York, New York, and Washington, D.C. For example, in Louisiana, the only Democratic delegate in US Congress who is a Democrat was elected from a district comprising in New Orleans. Below is a list of states and the major city/cities that provide much of the liberal support in them :\n\n Atlanta, Georgia: 5 of the 16 delegates representing Georgia in the US Congress are Democrats. All hail from districts in Atlanta.\n New Orleans, Louisiana: the only Democratic delegate from Louisiana in the US Congress was elected from a New Orleans district.\n Kansas City, Kansas: the only Democratic congressman from Kansas was elected from a district in Kansas City.\n Las Vegas, Nevada: all of the Democrats in the US House who represent Nevada are from Las Vegas.\n Salt Lake City, Utah: the only Democrat representing Utah in the US Congress was elected from a Salt Lake City district.\n Chicago, Illinois: if it weren\'t for Chicago, the state of Illinois would be as conservative as Indiana.\n Louisville, Kentucky: the only Democrat representing Kentucky in the US Congress was elected from a Louisville district.\n\nWorld\'s largest cities\n\nThese cities have more than 10 million people and can be called megacities:\n Tokyo, Japan - 37+ million\n Mexico City, Mexico - 21 million\n Mumbai, India - 20 million\n São Paulo, Brazil - 18 million\n Lagos, Nigeria - 13 million\n Calcutta, India - 13 million\n Buenos Aires, Argentina - 12 million\n Seoul, South Korea - 12 million\n Beijing, China - 12 million\n Karachi, Pakistan - 12 million\n Dhaka, Bangladesh - 11 million\n Manila, Philippines - 11 million\n Cairo, Egypt - 11 million\n Osaka, Japan - 11 million\n Rio de Janeiro, Brazil - 11 million\n Tianjin, China - 10 million\n Moscow, Russia - 10 million\n Lahore, Pakistan - 10 million\n\nGallery of cities\n\nReferences'}
 Score: 13.495842320359888

Document: {'id': '89', 'url': 'https://simple.wikipedia.org/wiki/Beijing', 'title': 'Beijing', 'text': 'Beijing is the capital of the People\'s Republic of China. The city used to be known as Peking.  It is in the northern and eastern parts of the country. It is the world\'s most populous capital city.\n\nThe city of Beijing has played a very important role in the development of China. Many people from different cities and countries come to Beijing to look for better chances to find work. Nearly 15 million people live there. In 2008 Beijing hosted the Summer Olympic Games, and will host the 2022 Winter Olympic Games. It will be the only city to host both.\n\nBeijing is well known for its ancient history.  Since the Jin Dynasty, Beijing has been the capital of several dynasties (especially the later ones), including the Yuan, Ming, and Qing. There are many places of historic interest in Beijing.\n\nName\n\nThe Mandarin Chinese name of the city is Běijīng, which means "The Northern Capital". It got this name when the Yongle Emperor of the Ming family of rulers moved most of his government from Nanjing ("The Southern Capital") in the early 1400s.  In Chinese, Beijing\'s name is written  Today, people spell it "Beijing" because they use the pinyin way of spelling, which shows what the name should sound like in Mandarin. People used to spell it "Peking" because that was the spelling used by some of the first people from Europe to visit the Ming and write home about it; the Jesuits\' work was made popular by their French brother Du Halde. It then became the official Chinese Postal Map spelling around 1900 and continued to be used until pinyin became more popular.\n\nBeijing was also known as Beiping ("City of Northern Peace") between 1928 and 1949, when the Nationalists moved the Chinese capital to Nanjing and Chongqing.\n\nHistory \nThe center of Beijing was settled in the 1st millennium BC. In those days, the Kingdom of Yan (燕, Yān) set up their capital where Beijing is today. They called it Ji (蓟, Jì). After the Kingdom of Yan was destroyed, the city became smaller, although it was still an important place.\n\nBeijing became more important again in the 10th century, when the Jin dynasty set its capital there. This city was destroyed by Mongol forces in 1215.  Then in 1267, Mongols built a new city on the north side of the Jin capital, and called it "Great Capital" (大都, Dàdū), which was the beginning of modern Beijing. When Kublai Khan the Mongolian monarch, set up the Yuan dynasty, this city became his capital.\n\nThe Yuan Dynasty, Ming Dynasty and Qing dynasty all made Beijing their capital. When the Qing dynasty lost power and the Republic of China was set up, the new Republic moved its capital from Beijing to Nanjing. When the People\'s Republic of China seized power, Beijing became the capital of China again.\n\nIn 1989, there were protests in Tian\'anmen Square because some people wanted democracy.\n\nSpecial places\nImportant places in Beijing include:\n The Great Wall of China (Chángchéng), in the mountains between Beijing and the grasslands of Mongolia\n The Forbidden City (Gùgōng), the most important home of the emperors of Ming and Qing China\n Tian\'anmen Square (Tiān\'ānmén Guǎngchǎng), surrounded by China\'s most important government buildings and museums\n Jingshan & Beihai Parks, the hill overlooking the Forbidden City and the lake beside it, with many temples\n The Summer Palace (Yìhéyuán) and Old Summer Palace (Yuánmíng Yuán), the more natural home of the last Qing emperors and what is left of an older one\n Prince Gong\'s Mansion, a very nice old house for one of the Qing princes\n The Imperial Ancestral Temple (Tàimiào), where the emperors remembered the earlier people in their families\n The Temple of Heaven (Tiāntán) and Temple of the Earth (Dìtán), important places for China\'s old national religion\n The Temples of the Sun and the Moon, other important places for China\'s old national religion\n The Temple of Confucius and Imperial Academy, important places for China\'s old kind of education\n Niujie Mosque, a place for Beijing\'s Muslims and one of the city\'s oldest buildings\n The National and Urban Planning Museums\n Olympic Green, the park left from the 2008 Beijing Olympics\n Marco Polo Bridge, a very old bridge across the main river west of town\n Ming Tombs, where many Ming emperors were buried\n Zhoukoudian, caves in the mountains west of town where people lived long, long ago\n\nEducation \nBeijing is the education center of People\'s Republic of China. More than 500 famous universities of China are in Beijing.  They also include 5 of the top universities: Peking University, Tsinghua University, China People University, Beijing Normal University, and Beihang University. Beijing is also education center of China for teaching Chinese as a foreign language. The standard Chinese pronunciation is based on Beijing dialect, so over 70% foreigners who want to study Chinese go to Beijing for their studies.\n\nSources\n\nPages\n\nBooks\n . \n .\n\nOther websites \n\n Beijing Travel\n Beijing Travel Guide\n Voyage Pékin \n Photos of Beijing \n\n \nOlympic cities\nProvinces of China'}
 Score: 11.136052179348187


### Sources

- https://medium.com/@ramishamukhtar786/boolean-retrieval-model-be5843ae3c9e
- https://github.com/mayank-02/boolean-retrieval-model/tree/main
- https://www.imaurer.com/which-vector-similarity-metric-should-i-use/
- https://spotintelligence.com/2023/09/07/vector-space-model/
- https://medium.com/analytics-vidhya/tf-idf-term-frequency-technique-easiest-explanation-for-text-classification-in-nlp-with-code-8ca3912e58c3
- https://medium.com/@rebirth4vali/tf-idf-from-scratch-with-python-e22033bb99f
- https://melaniewalsh.github.io/Intro-Cultural-Analytics/05-Text-Analysis/03-TF-IDF-Scikit-Learn.html
- https://medium.com/@evertongomede/understanding-the-bm25-ranking-algorithm-19f6d45c6ce